export const options = {
  colors: ["#fff"],
  enableTooltip: false,
  deterministic: false,
  // fontFamily: "serif",
  fontSizes: [45, 90],
  // fontStyle: "normal",
  // fontWeight: "normal",
  padding: 10,
  rotations: 1,
  rotationAngles: [0],
  scale: "linear",
  spiral: "archimedean",
  transitionDuration: 2000,
};